FROM python:3.9-slim

WORKDIR /serving

COPY ./app.py /serving
COPY ./requirements.txt /serving
COPY ./log_reg_dist.sav /serving

RUN pip install --no-cache-dir -r requirements.txt

ARG SERVING_PORT
ENV SERVING_PORT=${SERVING_PORT}
EXPOSE ${SERVING_PORT}

ENV COMET_API_KEY comet_api

CMD exec gunicorn --bind 0.0.0.0:${SERVING_PORT} app:app