FROM python:3.9-slim

WORKDIR /app

COPY ./app.py /app
COPY ./requirements.txt /app
COPY ./log_reg_dist.sav /app

RUN pip install -r requirements.txt

# ARG SERVING_PORT
# ENV SERVING_PORT=${SERVING_PORT}
# EXPOSE ${SERVING_PORT}

EXPOSE 5000

ENV COMET_API_KEY comet_api

CMD exec gunicorn --bind 0.0.0.0:5000 app:app