FROM python:3.9-slim

WORKDIR /app

COPY ./requirements.txt /app
RUN pip install -r requirements.txt


COPY ./new_crawler.py /app
COPY ./process_new_dataset.py /app
COPY ./serving_client.py /app
COPY ./game_client.py /app
COPY ./streamlit_app.py /app

# COPY . /app

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py"]
# CMD ["streamlit", "run", "streamlit_app.py",  "--logger.level=debug"]
# CMD streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0