# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      args:
        ARG: SERVING_PORT=5000
    image: my-flask-app
    ports:
     - 5000:5000
    environment:
      - COMET_API_KEY=j3DrC3ChXkR42WfPCUh5EIkye
    networks:
      - mynetwork

  streamlit:
    build: 
      context: ./
      dockerfile: ./Dockerfile.streamlit
    ports:
      - 8501:8501
    depends_on:
      - serving
    image: streamlit-app
    networks:
      - mynetwork

networks:
  mynetwork: